/**
 * autoEmissionCalculator.js
 * Rule 7.1 — Auto Emission Calculation Service (Dev A)
 *
 * When Settings.autoEmissionCalc = true:
 *   carbonEmitted = activityValue * EmissionFactor.factor
 *
 * When Settings.autoEmissionCalc = false:
 *   Accept manual carbonEmitted from client input (validated >= 0).
 */

const EmissionFactor = require('../../models/EmissionFactor');
const Settings = require('../../models/Settings');

/**
 * Resolves carbonEmitted value based on the global autoEmissionCalc setting.
 *
 * @param {string|ObjectId} emissionFactorId  - The ID of the EmissionFactor document
 * @param {number}          activityValue     - Raw quantity (e.g., 100 kWh)
 * @param {number|undefined} manualCarbon     - Client-provided override (used if autoCalc = false)
 * @returns {Promise<{ carbonEmitted: number, autoGenerated: boolean }>}
 * @throws {Error} if factor not found or manual value invalid
 */
const calculateEmission = async (emissionFactorId, activityValue, manualCarbon) => {
  // Fetch global settings (fallback: auto-calc ON)
  const settings = await Settings.findOne();
  const autoCalc = settings ? settings.autoEmissionCalc : true;

  if (autoCalc) {
    // --- AUTO MODE ---
    const factorDoc = await EmissionFactor.findById(emissionFactorId);
    if (!factorDoc) {
      throw new Error(`Emission factor with ID "${emissionFactorId}" not found.`);
    }
    if (typeof factorDoc.factor !== 'number' || factorDoc.factor <= 0) {
      throw new Error(`Emission factor value is invalid for factor "${factorDoc.name}".`);
    }
    if (typeof activityValue !== 'number' || activityValue <= 0) {
      throw new Error('activityValue must be a positive number.');
    }

    const carbonEmitted = parseFloat((activityValue * factorDoc.factor).toFixed(6));
    return { carbonEmitted, autoGenerated: true };
  } else {
    // --- MANUAL MODE ---
    if (manualCarbon === undefined || manualCarbon === null) {
      throw new Error('carbonEmitted is required when auto-calculation is disabled (Settings.autoEmissionCalc = false).');
    }
    const parsed = parseFloat(manualCarbon);
    if (isNaN(parsed) || parsed < 0) {
      throw new Error('carbonEmitted must be a valid non-negative number in manual mode.');
    }
    return { carbonEmitted: parsed, autoGenerated: false };
  }
};

module.exports = { calculateEmission };
